name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  test:
    name: JDK ${{matrix.java-version}} JVM Tests
    strategy:
      matrix:
        java-version: [ 17 ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Maven tests
        run: mvn verify
      - name: Upload XBuilder e2e Yaml files
        uses: actions/upload-artifact@v4
        with:
          name: xbuilder-e2e-yaml
          path: xbuilder/quarkus-extension/integration-tests/src/test/resources/e2e/

  quarkus-extension:
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ xbuilder, xsender ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven tests
        run: mvn install -DskipTests
      - name: Download XBuilder e2e Yaml files
        uses: actions/download-artifact@v4
        with:
          name: xbuilder-e2e-yaml
          path: xbuilder/quarkus-extension/integration-tests/src/test/resources/e2e/
      - name: Maven IT tests
        run: mvn -Pnative-image install -f ${{ matrix.module }}/quarkus-extension/integration-tests/

  quarkus-supported-v:
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ xbuilder, xsender ]
        quarkus-version: [ 3.0.4.Final, 3.2.6.Final, 3.3.3 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven tests
        run: mvn install -DskipTests
      - name: Download XBuilder e2e Yaml files
        uses: actions/download-artifact@v4
        with:
          name: xbuilder-e2e-yaml
          path: xbuilder/quarkus-extension/integration-tests/src/test/resources/e2e/
      - name: Maven IT tests
        run: mvn -Pnative-image install -f ${{ matrix.module }}/quarkus-extension/integration-tests/ -Dquarkus.version=${{ matrix.quarkus-version }}

  xsender-springboot-extension:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven tests
        run: mvn install -DskipTests
      - name: Maven IT tests
        run: mvn install -f xsender/spring-boot-extension/integration-tests/

  xsender-springboot-supported-v:
    needs: [ xsender-springboot-extension ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        springboot-version: [ 3.0.0, 3.1.3 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven tests
        run: mvn install -DskipTests
      - name: Maven IT tests
        run: mvn install -f xsender/spring-boot-extension/integration-tests/ -Dspringboot.version=${{ matrix.springboot-version }}
