name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  test:
    name: JDK ${{matrix.java-version}} JVM Tests
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn verify

  quarkus-extension:
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative install
      - name: Build with Maven
        run: mvn -Pnative-image install -f quarkus-extension/integration-tests/

  quarkus-supported-versions:
    needs: [ quarkus-extension ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        quarkus-version: [ 2.16.4.Final, 2.14.3.Final, 2.12.3.Final ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative install
      - name: Build with Maven
        run: mvn -Pnative-image install -f quarkus-extension/integration-tests/ -Dquarkus.version=${{ matrix.quarkus-version }}

  springboot-extension:
    needs: [ test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Build with Maven
        run: mvn install -f spring-boot-extension/integration-tests/

  springboot-supported-versions:
    needs: [ springboot-extension ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        springboot-version: [ 2.7.9, 2.7.5, 2.7.0 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Build with Maven
        run: mvn install -f spring-boot-extension/integration-tests/ -Dspringboot.version=${{ matrix.springboot-version }}
