name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

env:
  CI: true

jobs:
  snapshots:
    name: Snapshots
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # OSSRH
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: OSSRH Snapshot
        run: mvn --batch-mode compile source:jar javadoc:jar deploy -Possrh -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.nexus_username }}
          MAVEN_PASSWORD: ${{ secrets.nexus_password }}
